---
title: example.com
announcement: "Now with announcements!"
tabs:
  - name: requests
    url: https://example.com
  - name: couch
    url: https://example.com
  - name: sick
    url: https://example.com
  - name: gazelleui
    url: https://example.com
  - name: manual
    url: https://example.com
  - name: tautulli
    url: https://example.com
  - name: portainer
    url: https://example.com/
