---
title: My Dashboard
announcement: Welcome to my dashboard!
username: admin  # Optional: remove or leave blank to disable auth
password: secret # Optional: remove or leave blank to disable auth
tabs:
  - name: Home
    url: https://example.com
  - name: Status
    url: https://.example.com
  - name: Status
    url: https://.example.com
